<a href="https://colab.research.google.com/github/lalitha-sahitya/Rainfall-prediction/blob/main/usa_rain_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os

In [3]:
!pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from opendatasets) (4.67.1)
Requirement already satisfied: kaggle in /usr/local/lib/python3.11/dist-packages (from opendatasets) (1.6.17)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from opendatasets) (8.1.8)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (1.17.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2024.12.14)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2.32.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (2.3.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from kaggle->opendatasets) (6.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.11/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->kaggle->opendatasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->kaggle->opendatasets) (3.10)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [4]:
import opendatasets as od
od.download('https://www.kaggle.com/datasets/waqi786/usa-rainfall-prediction-dataset-2024-2025')

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: sahityapalacharla
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/waqi786/usa-rainfall-prediction-dataset-2024-2025
Downloading usa-rainfall-prediction-dataset-2024-2025.zip to ./usa-rainfall-prediction-dataset-2024-2025

100%|██████████| 3.90M/3.90M [00:00<00:00, 5.76MB/s]

In [5]:
os.listdir('usa-rainfall-prediction-dataset-2024-2025')

['usa_rain_prediction_dataset_2024_2025.csv']

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [7]:
data=pd.read_csv('/content/usa-rainfall-prediction-dataset-2024-2025/usa_rain_prediction_dataset_2024_2025.csv')

In [8]:
data.head()

,Date,Location,Temperature,Humidity,Wind Speed,Precipitation,Cloud Cover,Pressure,Rain Tomorrow
0,2024-01-01,New York,87.524795,75.655455,28.379506,0.000000,69.617966,1026.030278,0
1,2024-01-02,New York,83.259325,28.712617,12.436433,0.526995,41.606048,995.962065,0
2,2024-01-03,New York,80.943050,64.740043,14.184831,0.916884,77.364763,980.796739,1
3,2024-01-04,New York,78.097552,59.738984,19.444029,0.094134,52.541196,979.012163,0
4,2024-01-05,New York,37.059963,34.766784,3.689661,1.361272,85.584000,1031.790859,0

In [10]:
data.shape

(73100, 9)

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           73100 non-null  object
 1   Location       73100 non-null  object
 2   Temperature    73100 non-null  float64
 3   Humidity       73100 non-null  float64
 4   Wind Speed     73100 non-null  float64
 5   Precipitation  73100 non-null  float64
 6   Cloud Cover    73100 non-null  float64
 7   Pressure       73100 non-null  float64
 8   Rain Tomorrow  73100 non-null  int64
dtypes: float64(6), int64(1), object(2)
memory usage: 5.0+ MB

In [14]:
data.isna().sum()

Date             0
Location         0
Temperature      0
Humidity         0
Wind Speed       0
Precipitation    0
Cloud Cover      0
Pressure         0
Rain Tomorrow    0
dtype: int64

In [16]:
px.histogram(data,x='Location',color='Rain Tomorrow')

In [34]:
for i in data.select_dtypes(include='number').columns:
  fig=px.histogram(data,x=i,color='Rain Tomorrow')
  fig.show()

In [35]:
data.Location.unique().sum()

'New YorkLos AngelesChicagoHoustonPhoenixPhiladelphiaSan AntonioSan DiegoDallasSan JoseAustinJacksonvilleFort WorthColumbusIndianapolisCharlotteSan FranciscoSeattleDenverWashington D.C.'

In [36]:
from sklearn.preprocessing import LabelEncoder
enc=LabelEncoder()
data['Location']=enc.fit_transform(data['Location'])

In [37]:
data.head()

,Date,Location,Temperature,Humidity,Wind Speed,Precipitation,Cloud Cover,Pressure,Rain Tomorrow
0,2024-01-01,11,87.524795,75.655455,28.379506,0.000000,69.617966,1026.030278,0
1,2024-01-02,11,83.259325,28.712617,12.436433,0.526995,41.606048,995.962065,0
2,2024-01-03,11,80.943050,64.740043,14.184831,0.916884,77.364763,980.796739,1
3,2024-01-04,11,78.097552,59.738984,19.444029,0.094134,52.541196,979.012163,0
4,2024-01-05,11,37.059963,34.766784,3.689661,1.361272,85.584000,1031.790859,0

In [38]:
data.Location.unique()

array([11, 10,  2,  7, 13, 12, 14, 15,  4, 17,  0,  9,  6,  3,  8,  1, 16,
       18,  5, 19])

In [40]:
data['year']=pd.to_datetime(data.Date).dt.year

In [41]:
data.head()

,Date,Location,Temperature,Humidity,Wind Speed,Precipitation,Cloud Cover,Pressure,Rain Tomorrow,year
0,2024-01-01,11,87.524795,75.655455,28.379506,0.000000,69.617966,1026.030278,0,2024
1,2024-01-02,11,83.259325,28.712617,12.436433,0.526995,41.606048,995.962065,0,2024
2,2024-01-03,11,80.943050,64.740043,14.184831,0.916884,77.364763,980.796739,1,2024
3,2024-01-04,11,78.097552,59.738984,19.444029,0.094134,52.541196,979.012163,0,2024
4,2024-01-05,11,37.059963,34.766784,3.689661,1.361272,85.584000,1031.790859,0,2024

In [42]:
data['month']=pd.to_datetime(data.Date).dt.month

In [43]:
data['day']=pd.to_datetime(data.Date).dt.day

In [44]:
data.head()

,Date,Location,Temperature,Humidity,Wind Speed,Precipitation,Cloud Cover,Pressure,Rain Tomorrow,year,month,day
0,2024-01-01,11,87.524795,75.655455,28.379506,0.000000,69.617966,1026.030278,0,2024,1,1
1,2024-01-02,11,83.259325,28.712617,12.436433,0.526995,41.606048,995.962065,0,2024,1,2
2,2024-01-03,11,80.943050,64.740043,14.184831,0.916884,77.364763,980.796739,1,2024,1,3
3,2024-01-04,11,78.097552,59.738984,19.444029,0.094134,52.541196,979.012163,0,2024,1,4
4,2024-01-05,11,37.059963,34.766784,3.689661,1.361272,85.584000,1031.790859,0,2024,1,5

In [46]:
data=data.drop('Date',axis=1)

In [47]:
data.year.unique()

array([2024, 2025], dtype=int32)

In [48]:
data.month.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)

In [49]:
data.day.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
      dtype=int32)

In [50]:
data['year']=enc.fit_transform(data['year'])

In [51]:
data.head()

,Location,Temperature,Humidity,Wind Speed,Precipitation,Cloud Cover,Pressure,Rain Tomorrow,year,month,day
0,11,87.524795,75.655455,28.379506,0.000000,69.617966,1026.030278,0,0,1,1
1,11,83.259325,28.712617,12.436433,0.526995,41.606048,995.962065,0,0,1,2
2,11,80.943050,64.740043,14.184831,0.916884,77.364763,980.796739,1,0,1,3
3,11,78.097552,59.738984,19.444029,0.094134,52.541196,979.012163,0,0,1,4
4,11,37.059963,34.766784,3.689661,1.361272,85.584000,1031.790859,0,0,1,5

In [52]:
x=data.drop('Rain Tomorrow',axis=1)
y=data['Rain Tomorrow']

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [55]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [58]:
x_train=pd.DataFrame(x_train,columns=x.columns)
x_test=pd.DataFrame(x_test,columns=x.columns)

In [59]:
x_train.head()

,Location,Temperature,Humidity,Wind Speed,Precipitation,Cloud Cover,Pressure,year,month,day
0,-0.436047,1.445807,-1.291622,1.397614,-0.822478,-1.262317,-0.429521,0.999453,-0.439066,0.709972
1,0.429987,-1.128672,0.537128,-0.362093,-0.822478,0.911301,-0.729377,0.999453,-0.729482,-0.424642
2,-0.436047,-0.176521,0.419596,1.263641,1.259092,0.400804,-1.255398,0.999453,0.141767,1.390740
3,0.949608,1.364876,1.345674,0.169515,-0.822478,0.453947,1.441398,-1.000547,0.432183,-0.991949
4,-1.302082,-1.140479,0.476044,-1.538417,-0.822478,-1.244209,-0.321947,-1.000547,0.141767,-0.197719

In [60]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [61]:
preds=model.predict(x_test)

In [63]:
from sklearn.metrics import accuracy_score

In [65]:
accuracy_score(y_test,preds)

0.9090287277701778

In [66]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [67]:
preds=model.predict(x_test)

In [68]:
accuracy_score(y_test,preds)

1.0